ci:
  collect:
    numberOfRuns: 1
    url:
     - https://wieldy.app/
     - https://wieldy.app/changelog/
  assert:
    preset: lighthouse:recommended
    assertions:
      #offscreen-images: 'off'
      #uses-webp-images: 'off'
      color-contrast: 'off'
      is-crawlable: 'off'
      #first-contentful-paint:
      #  - error
      #  - maxNumericValue: 2000
      #    aggregationMethod: optimistic
      #interactive:
      #  - error
      #  - maxNumericValue: 5000
      #    aggregationMethod: optimistic
  upload:
    target: lhci
    serverBaseUrl: https://lhci.wieldy.app
