name: CI

on: 
  deployment:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - uses: Azure/docker-login@v1
      with:
        login-server: wieldy.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - run: |
        VERSION_PREFIX=$(grep '<VersionPrefix>' sync.csproj | sed "s@.*<VersionPrefix>\(.*\)</VersionPrefix>.*@\1@")
        VERSION_SUFFIX=$(grep '<VersionSuffix>' sync.csproj | sed "s@.*<VersionSuffix>\(.*\)</VersionSuffix>.*@\1@")        
        BUILD_VERSION=$(echo ${{ github.sha }} | awk '{print substr($0, length($0)-7)}')
        SYNC_VERSION=$(echo ${{format('{0}-{1}.{2}', '${VERSION_PREFIX}', '${VERSION_SUFFIX}', github.sha)}})
        echo "SYNC_VERSION=$SYNC_VERSION" >> $GITHUB_ENV
#        docker build . -t wieldy.azurecr.io/k8sdemo:${VERSION}
#        docker push wieldy.azurecr.io/k8sdemo:${VERSION}
        
    - run: |
        VERSION_PREFIX=$(grep '<VersionPrefix>' hello.csproj | sed "s@.*<VersionPrefix>\(.*\)</VersionPrefix>.*@\1@")
        VERSION_SUFFIX=$(grep '<VersionSuffix>' hello.csproj | sed "s@.*<VersionSuffix>\(.*\)</VersionSuffix>.*@\1@")        
        BUILD_VERSION=$(echo ${{ github.sha }} | awk '{print substr($0, length($0)-7)}')
        API_VERSION=$(echo ${{format('{0}-{1}.{2}', '${VERSION_PREFIX}', '${VERSION_SUFFIX}', github.run_number)}})
        echo "API_VERSION=$API_VERSION" >> $GITHUB_ENV
#        echo "::set-env name=API_VERSION::$API_VERSION"
        
    - run: |
        VERSION_PREFIX=$(grep '<VersionPrefix>' world.csproj | sed "s@.*<VersionPrefix>\(.*\)</VersionPrefix>.*@\1@")
        VERSION_SUFFIX=$(grep '<VersionSuffix>' world.csproj | sed "s@.*<VersionSuffix>\(.*\)</VersionSuffix>.*@\1@")        
        BUILD_VERSION=$(echo ${{ github.sha }} | awk '{print substr($0, length($0)-7)}')
        WEB_VERSION=$(echo ${{format('{0}-{1}.{2}', '${VERSION_PREFIX}', '${VERSION_SUFFIX}', github.run_number)}})
        echo "WEB_VERSION=$WEB_VERSION" >> $GITHUB_ENV
#        echo "::set-env name=WEB_VERSION::$WEB_VERSION"        
                
#    - uses: steebchen/kubectl@master
#      env:
#        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
#      with:
#        args: set image --record deployment/sync sync=wieldy.azurecr.io/sync-service:0.0.1-preview.11
#
#    - uses: steebchen/kubectl@master
#      env:
#        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
#      with:
#        args: set image --record deployment/api api=wieldy.azurecr.io/api-service:0.0.1-preview.104
#
#    - uses: steebchen/kubectl@master
#      env:
#        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
#      with:
#        args: set image --record deployment/web web=wieldy.azurecr.io/web-service:0.0.1-preview.324

    - name: Update deployment status (in_progress)
      if: success()
      uses: chrnorm/deployment-status@releases/v1
      with:
        token: "${{ github.token }}"
        target_url: https://wieldy.app
        state: "in_progress"
        deployment_id: ${{ github.event.deployment.id }}
        
    - uses: steebchen/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        KUBECTL_VERSION: "1.15"
      with:
        args: rollout status deployment/sync
          
    - uses: steebchen/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        KUBECTL_VERSION: "1.15"
      with:
        args: rollout status deployment/api

    - uses: steebchen/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        KUBECTL_VERSION: "1.15"
      with:
        args: rollout status deployment/web

#    - uses: actions/checkout@v2
#    - name: Create Sentry release
#      uses: getsentry/action-release@v1
#      env:
#        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
#        SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
#        SENTRY_PROJECT: helloworld
#      with:
#        environment: production
#        version: '${WEB_VERSION}'
    
    - name: Ending action
      run: |
        echo $WEB_VERSION
        echo $API_VERSION
        echo $SYNC_VERSION
        GH_REF=$(echo ${{ github.ref }})
        echo $GH_REF

    - name: Update deployment status (success)
      if: success()
      uses: chrnorm/deployment-status@releases/v1
      with:
        token: "${{ github.token }}"
        target_url: https://wieldy.app
        state: "success"
        deployment_id: ${{ github.event.deployment.id }}

    - name: Update deployment status (failure)
      if: failure()
      uses: chrnorm/deployment-status@releases/v1
      with:
        token: "${{ github.token }}"
        target_url: https://wieldy.app
        state: "failure"
        deployment_id: ${{ github.event.deployment.id }}

