name: CI

on: [deployment]

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      ENVIRONMENT: ${{ github.event.deployment.environment }}
      
    if: github.event.deployment.environment == 'foo'
    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: update deploy status
      if: always()
      uses: unacast/actions-github-deployment-status@0.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        status: ${{ job.status }}        
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - run: |
        az aks list
    - name: verify deployment
      uses: steebchen/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        KUBECTL_VERSION: "1.15"
      with:
        args: '"rollout status deployment/web"'      
