name: CI

on: [deployment]

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      ENVIRONMENT: ${{ github.event.deployment.environment }}
      
    if: github.event.deployment.environment == 'foo'
    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo $ENVIRONMENT miljö
        echo Add other actions to build,
        echo test, and deploy your project.
