# This is a basic workflow to help you get started with Actions

name: Security Headers

on:
  schedule:
    - cron: 0 0 * * *

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: marcuslindblom/security-headers
      - uses: marcuslindblom/security-headers@main
        with:
          url: ${{ secrets.SECURITY_HEADERS_URL }}
