name: Security Headers

on: [deployment]

jobs:
  check:
    runs-on: ubuntu-latest
    if: github.event.deployment.environment == 'production' && github.event.deployment_status.state == 'success'
    steps:
      - uses: actions/checkout@v2
        with:
          repository: marcuslindblom/security-headers
      - uses: marcuslindblom/security-headers@main
        with:
          url: ${{ secrets.SECURITY_HEADERS_URL }}
