# This is a basic workflow to help you get started with Actions

name: TEST

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
#  push:
#    branches: 
#      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    if: github.event.pull_request.draft == false
    name: Bulid and deploy
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Create GitHub deployment
        uses: bobheadxi/deployments@master
        id: deployment
        with:
          step: start
          token: ${{ secrets.DEPLOY_TOKEN }}
          env: production
          ref: ${{ github.head_ref }}
          desc: "Hello, world"

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Update GitHub deployment status
        uses: bobheadxi/deployments@master
        if: success()
        with:
          step: finish
          token: ${{ secrets.DEPLOY_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env_url: https://wieldy.app/
  
  lighthouse-check:
      if: success()
      needs: [build]
      name: Lighthouse Audit
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: run Lighthouse CI
        env:
          LHCI_TOKEN: ${{ secrets.LHCI_TOKEN }}
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        run: |
          npm install -g @lhci/cli@0.6.x
          lhci autorun --config=.github/lighthouse/lighthouserc.yml

  security-headers-check:
    needs: [build]
    name: Analyse HTTP response headers
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2
        with:
          repository: marcuslindblom/security-headers
      - uses: marcuslindblom/security-headers@main
        with:
          url: ${{ secrets.SECURITY_HEADERS_URL }}
          grade: C

  yellow-lab-tools-check:
    needs: [build]
    name: Detect performance and front-end issues
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: marcuslindblom/yellow-lab-tools
      - uses: marcuslindblom/yellow-lab-tools@main
        with:
          url: ${{ secrets.SECURITY_HEADERS_URL }}
          score: 100
          host: ${{ secrets.YELLOW_LAB_TOOLS_HOST }}
